In [2]:
!nvidia-smi

Mon Oct 23 05:31:42 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   42C    P8    15W /  70W |      2MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [10]:
!pip list

Package                       Version
----------------------------- --------------
aniso8601                     9.0.1
ansi2html                     1.8.0
anyio                         3.6.2
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
asttokens                     2.2.1
attrs                         22.2.0
awscli                        1.22.101
Babel                         2.11.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
beautifulsoup4                4.11.1
bleach                        5.0.1
blis                          0.7.9
bokeh                         2.4.3
boto3                         1.26.41
botocore                      1.29.41
brotlipy                      0.7.0
captum                        0.5.0
catalogue                     2.0.8
certifi                       2022.12.7
cffi                          1.15.1
charset-normalizer            2.1.1
click                         8.1.3


In [3]:
%matplotlib inline
import torch
import numpy as np

In [8]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


# Initializing a tensor

Tensors can be initialized in various ways. Take a look at the following examples.

## Directly from data

Tensors can be created directly from data. The data type is automatically inferred.

In [9]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

## From a NumPy array

Tensors can be created from NumPy arrays and vice versa.  Since, numpy _'np_array'_ and tensor _'x_np'_ share the same memory location here, changing the value for one will change the other.  

In [10]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(f"Numpy np_array value: \n {np_array} \n")
print(f"Tensor x_np value: \n {x_np} \n")

np.multiply(np_array, 2, out=np_array)

print(f"Numpy np_array after * 2 operation: \n {np_array} \n")
print(f"Tensor x_np value after modifying numpy array: \n {x_np} \n")

Numpy np_array value: 
 [[1 2]
 [3 4]] 

Tensor x_np value: 
 tensor([[1, 2],
        [3, 4]]) 

Numpy np_array after * 2 operation: 
 [[2 4]
 [6 8]] 

Tensor x_np value after modifying numpy array: 
 tensor([[2, 4],
        [6, 8]]) 



## From another tensor

The new tensor retains the properties (shape, data type) of the argument tensor, unless explicitly overridden.

In [11]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7621, 0.6109],
        [0.4521, 0.4448]]) 



## With random or constant values

`shape` is defined by a tuple of tensor dimensions, which set the number of rows and columns in a tensor. In the functions below, `shape` determines the dimensionality of the output tensor. 

In [12]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3153, 0.3145, 0.1722],
        [0.5322, 0.2878, 0.1126]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Attributes of a tensor

Tensor attributes describe their shape, data type, and the device on which they are stored.



In [13]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Operations on tensors

There are more than 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (such as transposing, indexing, and slicing). For sampling and reviewing, you'll find a comprehensive description [here](https://pytorch.org/docs/stable/torch.html).

Each of these operations can be run on the GPU (at typically higher speeds than on a
CPU).
- CPUs have up to 16 cores. Cores are units that do the actual computation. Each core processes tasks in a sequential order (one task at a time).
- GPUs have 1000s of cores.  GPU cores handle computations in parallel processing. Tasks are divided and processed across the different cores. That's what makes GPUs faster than CPUs in most cases. GPUs perform better with large data than small data. GPU are typically used for high-intensive computation of graphics or neural networks (we'll learn more about that later in the Neural Network unit).
- PyTorch can use the Nvidia CUDA library to take advantage of their GPU cards.

<img alt="Diagram showing workload between cpu and gpu." src="../images/2-tensor-2.png"/>

By default, tensors are created on the CPU. Tensors can also be computed to GPUs; to do that, you need to move them using the `.to` method (after checking for GPU availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!


In [14]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

## Standard numpy-like indexing and slicing

## Joining tensors
You can use [`torch.cat`](https://pytorch.org/docs/stable/generated/torch.cat.html) to concatenate a sequence of tensors along a *given* dimension.
[`torch.stack`](https://pytorch.org/docs/stable/generated/torch.stack.html) is a related tensor joining option that concatenates a sequence of tensors along a *new* dimension.

In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.0050, 0.2928, 0.1820, 0.5442, 0.0050, 0.2928, 0.1820, 0.5442, 0.0050,
         0.2928, 0.1820, 0.5442],
        [0.2293, 0.2239, 0.0637, 0.7417, 0.2293, 0.2239, 0.0637, 0.7417, 0.2293,
         0.2239, 0.0637, 0.7417],
        [0.5518, 0.0411, 0.5066, 0.6727, 0.5518, 0.0411, 0.5066, 0.6727, 0.5518,
         0.0411, 0.5066, 0.6727]])


## Arithmetic operations

In [16]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

/tmp/ipykernel_2599/2653314025.py:6: UserWarning: An output with one or more elements was resized since it had shape [3, 4], which does not match the required output shape [3, 3]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  torch.matmul(tensor, tensor.T, out=y3)


tensor([[2.4711e-05, 8.5736e-02, 3.3119e-02, 2.9616e-01],
        [5.2561e-02, 5.0133e-02, 4.0585e-03, 5.5019e-01],
        [3.0452e-01, 1.6905e-03, 2.5664e-01, 4.5254e-01]])

## Single-element tensors
If you have a one-element tensor, for example by aggregating all
values of a tensor into one value, you can convert it to a Python
numerical value using `item()`:

In [17]:
agg = tensor.sum()
agg_item = agg.item()  
print(agg_item, type(agg_item))

4.05484676361084 <class 'float'>


## In-place operations
Operations that store the result into the operand are called in-place. They are denoted by a ``_`` suffix. 
For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.

> **Note:** In-place operations save some memory, but can be problematic when computing derivatives because of their immediate loss of history. Hence, their use is discouraged.



In [18]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[0.0050, 0.2928, 0.1820, 0.5442],
        [0.2293, 0.2239, 0.0637, 0.7417],
        [0.5518, 0.0411, 0.5066, 0.6727]]) 

tensor([[5.0050, 5.2928, 5.1820, 5.5442],
        [5.2293, 5.2239, 5.0637, 5.7417],
        [5.5518, 5.0411, 5.5066, 5.6727]])


## Bridge with NumPy

Tensors on the CPU and NumPy arrays can share their underlying memory
locations, and changing one will change	the other.

### Tensor to NumPy array

In [19]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.

In [20]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy array to tensor

In [21]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.

In [22]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
